from config import settings
from langchain_google_genai import ChatGoogleGenerativeAI

def main():
    # ChatGoogleGenerativeAI is LangChain's specific integration class for Google's Gemini models.
    # LangChain uses these classes to standardize interactions, so whether you use Gemini, OpenAI,
    # or another provider, the way you call it (like .invoke()) remains exactly the same.
    #
    # temperature=0 sets the randomness of the model to the absolute minimum.
    # This means the model will almost always choose the most likely next word,
    # leading to highly deterministic, focused, and factual responses. This is usually
    # preferred for RAG (Retrieval-Augmented Generation) where accuracy is key.
    llm = ChatGoogleGenerativeAI(
        model="gemini-3.5-flash",
        temperature=0,
        api_key=settings.GOOGLE_API_KEY
    )

    print("Sending prompt to Gemini...\n")
    
    # The invoke() method is LangChain's unified way to execute a model or a chain.
    # Here, we pass a simple string. The LLM processes it and returns an AIMessage object.
    response = llm.invoke("What is an AI agent?")

    # response.content accesses the actual text generated by the LLM,
    # ignoring other metadata (like token usage or finish reasons) that comes back in the object.
    print(response.content)

if __name__ == "__main__":
    main()
