from .config import settings
from .core.llm_factory import get_llm

def main():
    # We now fetch the LLM from our factory, which reads the LLM_PROVIDER env variable.
    # This allows us to seamlessly swap between Gemini and Groq without changing this code.
    llm = get_llm()

    print("Sending prompt to Gemini...\n")
    
    try:
        # The invoke() method is LangChain's unified way to execute a model or a chain.
        # Here, we pass a simple string. The LLM processes it and returns an AIMessage object.
        response = llm.invoke("Who is CJP ?")

        # response.content accesses the actual text generated by the LLM,
        # ignoring other metadata (like token usage or finish reasons) that comes back in the object.
        print(response.content)
    except Exception:
        print("Gemini models are down from google side only")

if __name__ == "__main__":
    main()
